split ecs out ready for a lambda scanner
ministryofjustice/securityanalytics-nmapscanner pull request #41
Opened 2019-05-14 20:22 UTC by progers-SL

2019-05-15 10:13 UTC, blackmamo requested changes
This has not been done in a way to make the user interface simple. The user has to import 2 modules where previously they only needed to import 1

2019-05-15 10:13 UTC, blackmamo commented on .vscode/settings.json
> +{
Please don't commit IDE specific files, add to your .git/info/exclude

2019-05-15 10:13 UTC, blackmamo commented on infrastructure/docker_image/Dockerfile.template
> +
Non semantic change, and no improvement, please remove the noise

2019-05-15 10:13 UTC, blackmamo commented on infrastructure/infrastructure.tf
> +module "nmap_task_shared" {
I really don't like this shared name. We are not sharing this module. nmap_task_resources?

2019-05-15 10:13 UTC, blackmamo commented on infrastructure/infrastructure.tf
> +  // two slashes are intentional: https://www.terraform.io/docs/modules/sources.html#modules-in-package-sub-directories  # source = "github.com/ministryofjustice/securityanalytics-taskexecution//infr
Don't need that additional commented out line here

2019-05-15 10:13 UTC, blackmamo commented on infrastructure/infrastructure.tf
> +module "nmap_task_shared" {
We don't want to have to import two modules here. We only want to import the ecs_task. The ecs_task should itself use the simpler module

2019-05-22 08:55 UTC, progers-SL commented
not needed

2019-05-22 08:55 UTC, closed without merging