scan all ports
ministryofjustice/securityanalytics-nmapscanner pull request #64
Opened 2019-07-05 13:51 UTC by progers-SL

mo' ports

2019-07-08 16:59 UTC, blackmamo requested changes
I think that this is probably updated now anyway since you showed me this with sliders, but can we not hardcode 443, 80, 22?. CAn you also check that task execution and shared code references are updated to latest on master

2019-07-08 16:59 UTC, blackmamo commented on infrastructure/elastic_resources/searches/non_standard_ports.search.json
> +        "description": "A search returning all IP addresses where a port is open that isn't 80, 443, 22, and some mail ones",
Do we want to hard code these or use sliders?

2019-07-15 09:35 UTC, blackmamo requested changes

2019-07-15 09:35 UTC, blackmamo commented on infrastructure/elastic_resources/dashboards.tf
> +  // It is sometimes useful for the developers of the project to use a local version of the task
# not // please, this applies to all chages

2019-07-15 09:35 UTC, blackmamo commented on infrastructure/docker_image/Dockerfile.template
> +ENTRYPOINT [ "sh", "task_script.sh", "--resolve-all", "--script", "ssl-enum-ciphers,vulners,ssl-cert", "-A", "-v", "-sT", "-p0-65535", "-T4"]
We now have way too many arguments to not comment on them. We should explain exactly what options we are passing and why

2019-07-15 09:35 UTC, blackmamo commented on results_parser/ssl-cert.py
> +                if elem["key"] == "notAfter":
This method is a bit of a monster now. PLease consider splitting it up as a way to add more names and extend understanding

2019-07-15 09:40 UTC, closed without merging

2019-07-15 09:40 UTC, progers-SL commented
in the other PR